import { nav } from './nav.js';
import { checkPiece } from './cartItem.js';
import { openSearch } from './openSearch.js';
import { searchCard } from './searchCard.js';
import { preloader } from './_preloader.js';
preloader();
searchCard();
openSearch();
checkPiece();
nav();
